### PR TITLE
[WIP] Change UpdateTemplate function declaration

### LINKED ISSUE #8: Change UpdateTemplate in InMemoryStore to take map as input

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #8.

### CODE REVIEW

**Comment by captainsafia** [comment]
Having a problem with this @rgbkrk so leaving a note here for whenever you can get to it.

I'm having an issue when trying to run `go tests`, specifically with the mocks. Since I altered the store interface I ran `$GOPATH/bin/mockery --all` to regenerate the mocks which are then stored in the `mocks` folder. However, the `setupHandlersTests` function in `handlers_test.go` refers to the `mockStore` struct in `registry_test.go` which isn't updated when I run `mockery`. I'm not entire sure why the Store mock was set up this way either. Furthermore, how exactly was the mockStore created?

Let me know if any of that doesn't make sense.

**Comment by rgbkrk** [comment]
I shoe horned the mockStore into working. The reflection was not working well so I wrote a way to work with it. We can and should do those differently.

**Comment by captainsafia** [comment]
Hm I see. I'll give refactoring the mocks ago. Right now, if you trying using mocks.Store you get all the import cycle errors one can possibly contain in a 80 character by 194 character terminal.

**Comment by captainsafia** [comment]
gopher_gorequest_400x300

Me working on binder-registry looks a lot like this.

**Comment by captainsafia** [comment]
Wow. More than 4 years ago. Time to close this.

**Pull request closed without merging**
